# Generated by Django 4.2.7 on 2024-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
