# Generated by Django 4.2.7 on 2024-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_preco_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tamanho',
            field=models.ManyToManyField(to='pedidos.preco'),
        ),
    ]
