# Generated by Django 4.2.7 on 2024-03-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tamanho', models.CharField(choices=[['Broto', '4 pedaços'], ['Pequena', '6 pedaços'], ['Média', '8 pedaços'], ['Grande', '12 pedaços'], ['Familia', '16 pedaços']], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pizzas', models.ManyToManyField(to='pizza.pizza')),
            ],
        ),
    ]
