# Generated by Django 4.2.7 on 2024-03-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='tamanho',
        ),
    ]
