# Generated by Django 4.2.7 on 2024-03-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_remove_pizza_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='preço',
        ),
    ]
