# Generated by Django 4.2.7 on 2024-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_remove_pizza_preço'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tamanho', models.CharField(choices=[['Broto', '4 pedaços'], ['Pequena', '6 pedaços'], ['Média', '8 pedaços'], ['Grande', '12 pedaços'], ['Familia', '16 pedaços']], max_length=10)),
            ],
        ),
    ]
