# Generated by Django 4.2.7 on 2024-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_tamanhos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_pizzas/')),
            ],
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pizzas',
            field=models.ManyToManyField(to='pizza.cardapio'),
        ),
    ]
