# Generated by Django 4.2.7 on 2024-03-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_cardapio_delete_pizza_alter_pedido_pizzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pizzas',
        ),
        migrations.DeleteModel(
            name='Tamanhos',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='sabor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pizza.sabores'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pizza.tamanho'),
        ),
    ]
