# Generated by Django 4.2.7 on 2024-04-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_pedidos_sabores_tamanho_remove_pedido_pizzas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sabores',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='tamanho',
            field=models.CharField(choices=[('B', 'Broto'), ('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande'), ('F', 'Família')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
