# Generated by Django 4.2.7 on 2024-04-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_remove_pedidos_email_remove_sabores_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('B', 'Broto'), ('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande'), ('F', 'Família')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.tamanho'),
        ),
    ]
