# Generated by Django 4.2.7 on 2024-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_tamanho_alter_pedidos_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='tamanho',
            field=models.CharField(choices=[('B', 'Broto'), ('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande'), ('F', 'Família')], max_length=1),
        ),
    ]
