# Generated by Django 4.2.7 on 2024-04-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_alter_pedidos_tamanho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
