# Generated by Django 4.2.7 on 2024-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_delete_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='observacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
