# Generated by Django 4.2.7 on 2024-04-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_pedidos_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='sabor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pizza.sabores'),
        ),
    ]
