# Generated by Django 4.2.7 on 2024-04-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0012_alter_pedidos_sabor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='sabor',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='sabores',
            field=models.ManyToManyField(to='pizza.sabores'),
        ),
    ]
